/**
 * Generated Routes Manifest
 *
 * DO NOT EDIT - This file is auto-generated by route.generator.ts
 * Run: deno task routes:generate
 */

import type { RoutesManifest } from '@emkodev/emroute';

export const routesManifest: RoutesManifest = {
  routes: [
  {
    pattern: '/html/nesting-ts/lvl-one/level-two/level-three/markdown',
    type: 'page',
    modulePath: 'routes/nesting-ts/lvl-one/level-two/level-three/markdown.page.md',
    files: { md: 'routes/nesting-ts/lvl-one/level-two/level-three/markdown.page.md' },
    parent: '/html/nesting-ts/lvl-one/level-two/level-three',
  },
  {
    pattern: '/html/nesting-ts/lvl-one/level-two/level-three/html',
    type: 'page',
    modulePath: 'routes/nesting-ts/lvl-one/level-two/level-three/html.page.html',
    files: { html: 'routes/nesting-ts/lvl-one/level-two/level-three/html.page.html' },
    parent: '/html/nesting-ts/lvl-one/level-two/level-three',
  },
  {
    pattern: '/html/nesting-ts/lvl-one/level-two/level-three/typescript',
    type: 'page',
    modulePath: 'routes/nesting-ts/lvl-one/level-two/level-three/typescript.page.ts',
    files: { ts: 'routes/nesting-ts/lvl-one/level-two/level-three/typescript.page.ts' },
    parent: '/html/nesting-ts/lvl-one/level-two/level-three',
  },
  {
    pattern: '/html/nesting-ts-md/lvl-one/level-two/level-three',
    type: 'page',
    modulePath: 'routes/nesting-ts-md/lvl-one/level-two/level-three.page.ts',
    files: { md: 'routes/nesting-ts-md/lvl-one/level-two/level-three.page.md', ts: 'routes/nesting-ts-md/lvl-one/level-two/level-three.page.ts' },
    parent: '/html/nesting-ts-md/lvl-one/level-two',
  },
  {
    pattern: '/html/nesting/lvl-one/level-two/level-three',
    type: 'page',
    modulePath: 'routes/nesting/lvl-one/level-two/level-three.page.html',
    files: { html: 'routes/nesting/lvl-one/level-two/level-three.page.html', md: 'routes/nesting/lvl-one/level-two/level-three.page.md' },
    parent: '/html/nesting/lvl-one/level-two',
  },
  {
    pattern: '/html/nesting-ts-html/lvl-one/level-two/level-three',
    type: 'page',
    modulePath: 'routes/nesting-ts-html/lvl-one/level-two/level-three.page.ts',
    files: { html: 'routes/nesting-ts-html/lvl-one/level-two/level-three.page.html', ts: 'routes/nesting-ts-html/lvl-one/level-two/level-three.page.ts' },
    parent: '/html/nesting-ts-html/lvl-one/level-two',
  },
  {
    pattern: '/html/nesting-ts/lvl-one/level-two',
    type: 'page',
    modulePath: 'routes/nesting-ts/lvl-one/level-two.page.ts',
    files: { ts: 'routes/nesting-ts/lvl-one/level-two.page.ts' },
    parent: '/html/nesting-ts/lvl-one',
  },
  {
    pattern: '/html/nesting-ts-md/lvl-one/level-two',
    type: 'page',
    modulePath: 'routes/nesting-ts-md/lvl-one/level-two.page.ts',
    files: { md: 'routes/nesting-ts-md/lvl-one/level-two.page.md', ts: 'routes/nesting-ts-md/lvl-one/level-two.page.ts' },
    parent: '/html/nesting-ts-md/lvl-one',
  },
  {
    pattern: '/html/nesting/lvl-one/level-two',
    type: 'page',
    modulePath: 'routes/nesting/lvl-one/level-two.page.html',
    files: { html: 'routes/nesting/lvl-one/level-two.page.html', md: 'routes/nesting/lvl-one/level-two.page.md' },
    parent: '/html/nesting/lvl-one',
  },
  {
    pattern: '/html/nesting-ts-html/lvl-one/level-two',
    type: 'page',
    modulePath: 'routes/nesting-ts-html/lvl-one/level-two.page.ts',
    files: { html: 'routes/nesting-ts-html/lvl-one/level-two.page.html', ts: 'routes/nesting-ts-html/lvl-one/level-two.page.ts' },
    parent: '/html/nesting-ts-html/lvl-one',
  },
  {
    pattern: '/html/projects/:id/tasks',
    type: 'page',
    modulePath: 'routes/projects/[id]/tasks.page.ts',
    files: { ts: 'routes/projects/[id]/tasks.page.ts' },
    parent: '/html/projects/:id',
  },
  {
    pattern: '/html/articles/:slug/comment',
    type: 'page',
    modulePath: 'routes/articles/[slug]/comment.page.ts',
    files: { ts: 'routes/articles/[slug]/comment.page.ts' },
    parent: '/html/articles/:slug',
  },
  {
    pattern: '/html/projects/broken',
    type: 'page',
    modulePath: 'routes/projects/broken.page.ts',
    files: { ts: 'routes/projects/broken.page.ts' },
    parent: '/html/projects',
  },
  {
    pattern: '/html/nesting-ts/lvl-one',
    type: 'page',
    modulePath: 'routes/nesting-ts/lvl-one.page.ts',
    files: { ts: 'routes/nesting-ts/lvl-one.page.ts' },
    parent: '/html/nesting-ts',
  },
  {
    pattern: '/html/nesting-ts-md/lvl-one',
    type: 'page',
    modulePath: 'routes/nesting-ts-md/lvl-one.page.ts',
    files: { ts: 'routes/nesting-ts-md/lvl-one.page.ts', md: 'routes/nesting-ts-md/lvl-one.page.md' },
    parent: '/html/nesting-ts-md',
  },
  {
    pattern: '/html/vanilla/counter',
    type: 'page',
    modulePath: 'routes/vanilla/counter.page.md',
    files: { md: 'routes/vanilla/counter.page.md' },
    parent: '/html/vanilla',
  },
  {
    pattern: '/html/nesting/lvl-one',
    type: 'page',
    modulePath: 'routes/nesting/lvl-one.page.html',
    files: { html: 'routes/nesting/lvl-one.page.html', md: 'routes/nesting/lvl-one.page.md' },
    parent: '/html/nesting',
  },
  {
    pattern: '/html/nesting-ts-html/lvl-one',
    type: 'page',
    modulePath: 'routes/nesting-ts-html/lvl-one.page.ts',
    files: { ts: 'routes/nesting-ts-html/lvl-one.page.ts', html: 'routes/nesting-ts-html/lvl-one.page.html' },
    parent: '/html/nesting-ts-html',
  },
  {
    pattern: '/html/projects/:id',
    type: 'page',
    modulePath: 'routes/projects/[id].page.ts',
    files: { ts: 'routes/projects/[id].page.ts' },
    parent: '/html/projects',
  },
  {
    pattern: '/html/articles/:slug',
    type: 'page',
    modulePath: 'routes/articles/[slug].page.ts',
    files: { css: 'routes/articles/[slug].page.css', html: 'routes/articles/[slug].page.html', ts: 'routes/articles/[slug].page.ts' },
    parent: '/html/articles',
  },
  {
    pattern: '/html/profile',
    type: 'page',
    modulePath: 'routes/profile.page.ts',
    files: { ts: 'routes/profile.page.ts', html: 'routes/profile.page.html' },
  },
  {
    pattern: '/html/widgets-html',
    type: 'page',
    modulePath: 'routes/widgets-html.page.html',
    files: { html: 'routes/widgets-html.page.html' },
  },
  {
    pattern: '/html/projects',
    type: 'page',
    modulePath: 'routes/projects.page.md',
    files: { md: 'routes/projects.page.md' },
  },
  {
    pattern: '/html/articles',
    type: 'page',
    modulePath: 'routes/articles.page.ts',
    files: { html: 'routes/articles.page.html', ts: 'routes/articles.page.ts' },
  },
  {
    pattern: '/html/mixed-widgets',
    type: 'page',
    modulePath: 'routes/mixed-widgets.page.html',
    files: { html: 'routes/mixed-widgets.page.html', md: 'routes/mixed-widgets.page.md' },
  },
  {
    pattern: '/html/about',
    type: 'page',
    modulePath: 'routes/about.page.html',
    files: { md: 'routes/about.page.md', css: 'routes/about.page.css', html: 'routes/about.page.html' },
  },
  {
    pattern: '/html/nesting',
    type: 'page',
    modulePath: 'routes/nesting.page.html',
    files: { md: 'routes/nesting.page.md', html: 'routes/nesting.page.html' },
  },
  {
    pattern: '/html/empty-markdown',
    type: 'page',
    modulePath: 'routes/empty-markdown.page.html',
    files: { html: 'routes/empty-markdown.page.html' },
  },
  {
    pattern: '/html/nesting-ts',
    type: 'page',
    modulePath: 'routes/nesting-ts.page.ts',
    files: { ts: 'routes/nesting-ts.page.ts' },
  },
  {
    pattern: '/html/docs',
    type: 'page',
    modulePath: 'routes/docs.page.ts',
    files: { html: 'routes/docs.page.html', ts: 'routes/docs.page.ts' },
  },
  {
    pattern: '/html/crash',
    type: 'page',
    modulePath: 'routes/crash.page.ts',
    files: { ts: 'routes/crash.page.ts' },
  },
  {
    pattern: '/html/widgets',
    type: 'page',
    modulePath: 'routes/widgets.page.md',
    files: { md: 'routes/widgets.page.md' },
  },
  {
    pattern: '/html/blog',
    type: 'page',
    modulePath: 'routes/blog.page.ts',
    files: { md: 'routes/blog.page.md', ts: 'routes/blog.page.ts' },
  },
  {
    pattern: '/html/nesting-ts-md',
    type: 'page',
    modulePath: 'routes/nesting-ts-md.page.ts',
    files: { ts: 'routes/nesting-ts-md.page.ts', md: 'routes/nesting-ts-md.page.md' },
  },
  {
    pattern: '/html/nesting-ts-html',
    type: 'page',
    modulePath: 'routes/nesting-ts-html.page.ts',
    files: { html: 'routes/nesting-ts-html.page.html', ts: 'routes/nesting-ts-html.page.ts' },
  },
  {
    pattern: '/html/widget-files-md',
    type: 'page',
    modulePath: 'routes/widget-files-md.page.md',
    files: { md: 'routes/widget-files-md.page.md' },
  },
  {
    pattern: '/html/widget-files',
    type: 'page',
    modulePath: 'routes/widget-files.page.html',
    files: { html: 'routes/widget-files.page.html' },
  },
  {
    pattern: '/html/hydration',
    type: 'page',
    modulePath: 'routes/hydration.page.ts',
    files: { ts: 'routes/hydration.page.ts' },
  },
  {
    pattern: '/html/old',
    type: 'redirect',
    modulePath: 'routes/old.redirect.ts',
  },
  {
    pattern: '/html',
    type: 'page',
    modulePath: 'routes/index.page.md',
    files: { md: 'routes/index.page.md' },
  },
  {
    pattern: '/html/projects/:rest*',
    type: 'page',
    modulePath: 'routes/projects/index.page.md',
    files: { md: 'routes/projects/index.page.md' },
    parent: '/html/projects',
  }
  ],

  errorBoundaries: [
  {
    pattern: '/html/projects',
    modulePath: 'routes/projects/[id].error.ts',
  }
  ],

  statusPages: new Map([
  [404, { pattern: '/html/404', type: 'page', modulePath: 'routes/404.page.html', statusCode: 404, files: { html: 'routes/404.page.html', md: 'routes/404.page.md' } }]
  ]),

  errorHandler: {
  pattern: '/html',
  type: 'error',
  modulePath: 'routes/index.error.ts',
},

  moduleLoaders: {
    'routes/nesting-ts/lvl-one/level-two/level-three/typescript.page.ts': () => import('./routes/nesting-ts/lvl-one/level-two/level-three/typescript.page.ts'),
    'routes/nesting-ts-md/lvl-one/level-two/level-three.page.ts': () => import('./routes/nesting-ts-md/lvl-one/level-two/level-three.page.ts'),
    'routes/nesting-ts-html/lvl-one/level-two/level-three.page.ts': () => import('./routes/nesting-ts-html/lvl-one/level-two/level-three.page.ts'),
    'routes/nesting-ts/lvl-one/level-two.page.ts': () => import('./routes/nesting-ts/lvl-one/level-two.page.ts'),
    'routes/nesting-ts-md/lvl-one/level-two.page.ts': () => import('./routes/nesting-ts-md/lvl-one/level-two.page.ts'),
    'routes/nesting-ts-html/lvl-one/level-two.page.ts': () => import('./routes/nesting-ts-html/lvl-one/level-two.page.ts'),
    'routes/projects/[id]/tasks.page.ts': () => import('./routes/projects/[id]/tasks.page.ts'),
    'routes/articles/[slug]/comment.page.ts': () => import('./routes/articles/[slug]/comment.page.ts'),
    'routes/projects/broken.page.ts': () => import('./routes/projects/broken.page.ts'),
    'routes/nesting-ts/lvl-one.page.ts': () => import('./routes/nesting-ts/lvl-one.page.ts'),
    'routes/nesting-ts-md/lvl-one.page.ts': () => import('./routes/nesting-ts-md/lvl-one.page.ts'),
    'routes/nesting-ts-html/lvl-one.page.ts': () => import('./routes/nesting-ts-html/lvl-one.page.ts'),
    'routes/projects/[id].page.ts': () => import('./routes/projects/[id].page.ts'),
    'routes/articles/[slug].page.ts': () => import('./routes/articles/[slug].page.ts'),
    'routes/profile.page.ts': () => import('./routes/profile.page.ts'),
    'routes/articles.page.ts': () => import('./routes/articles.page.ts'),
    'routes/nesting-ts.page.ts': () => import('./routes/nesting-ts.page.ts'),
    'routes/docs.page.ts': () => import('./routes/docs.page.ts'),
    'routes/crash.page.ts': () => import('./routes/crash.page.ts'),
    'routes/blog.page.ts': () => import('./routes/blog.page.ts'),
    'routes/nesting-ts-md.page.ts': () => import('./routes/nesting-ts-md.page.ts'),
    'routes/nesting-ts-html.page.ts': () => import('./routes/nesting-ts-html.page.ts'),
    'routes/hydration.page.ts': () => import('./routes/hydration.page.ts'),
    'routes/old.redirect.ts': () => import('./routes/old.redirect.ts'),
    'routes/projects/[id].error.ts': () => import('./routes/projects/[id].error.ts'),
    'routes/index.error.ts': () => import('./routes/index.error.ts'),
  },
};
