/**
 * Generated Routes Manifest
 *
 * DO NOT EDIT - This file is auto-generated by route.generator.ts
 * Run: deno task routes:generate
 */

import type { RoutesManifest } from '@emkodev/emroute';

export const routesManifest: RoutesManifest = {
  routes: [
  {
    pattern: '/projects/:id/tasks',
    type: 'page',
    modulePath: 'routes/projects/[id]/tasks.page.ts',
    files: { ts: 'routes/projects/[id]/tasks.page.ts' },
    parent: '/projects/:id',
  },
  {
    pattern: '/projects/:id',
    type: 'page',
    modulePath: 'routes/projects/[id].page.ts',
    files: { ts: 'routes/projects/[id].page.ts' },
    parent: '/projects',
  },
  {
    pattern: '/profile',
    type: 'page',
    modulePath: 'routes/profile.page.ts',
    files: { ts: 'routes/profile.page.ts', html: 'routes/profile.page.html' },
  },
  {
    pattern: '/projects',
    type: 'page',
    modulePath: 'routes/projects.page.md',
    files: { md: 'routes/projects.page.md' },
  },
  {
    pattern: '/about',
    type: 'page',
    modulePath: 'routes/about.page.html',
    files: { html: 'routes/about.page.html' },
  },
  {
    pattern: '/docs',
    type: 'page',
    modulePath: 'routes/docs.page.ts',
    files: { html: 'routes/docs.page.html', ts: 'routes/docs.page.ts' },
  },
  {
    pattern: '/crash',
    type: 'page',
    modulePath: 'routes/crash.page.ts',
    files: { ts: 'routes/crash.page.ts' },
  },
  {
    pattern: '/blog',
    type: 'page',
    modulePath: 'routes/blog.page.ts',
    files: { md: 'routes/blog.page.md', ts: 'routes/blog.page.ts' },
  },
  {
    pattern: '/old',
    type: 'redirect',
    modulePath: 'routes/old.redirect.ts',
  },
  {
    pattern: '/',
    type: 'page',
    modulePath: 'routes/index.page.md',
    files: { md: 'routes/index.page.md' },
  },
  {
    pattern: '/projects/:rest*',
    type: 'page',
    modulePath: 'routes/projects/index.page.md',
    files: { md: 'routes/projects/index.page.md' },
    parent: '/projects',
  }
  ],

  errorBoundaries: [
  {
    pattern: '/projects',
    modulePath: 'routes/projects/[id].error.ts',
  }
  ],

  statusPages: new Map([
  [404, { pattern: '/404', type: 'page', modulePath: 'routes/404.page.html', statusCode: 404, files: { html: 'routes/404.page.html' } }]
  ]),

  errorHandler: {
  pattern: '/',
  type: 'error',
  modulePath: 'routes/error.ts',
},

  moduleLoaders: {
    'routes/projects/[id]/tasks.page.ts': () => import('./routes/projects/[id]/tasks.page.ts'),
    'routes/projects/[id].page.ts': () => import('./routes/projects/[id].page.ts'),
    'routes/profile.page.ts': () => import('./routes/profile.page.ts'),
    'routes/docs.page.ts': () => import('./routes/docs.page.ts'),
    'routes/crash.page.ts': () => import('./routes/crash.page.ts'),
    'routes/blog.page.ts': () => import('./routes/blog.page.ts'),
    'routes/old.redirect.ts': () => import('./routes/old.redirect.ts'),
    'routes/projects/[id].error.ts': () => import('./routes/projects/[id].error.ts'),
    'routes/error.ts': () => import('./routes/error.ts'),
  },
};
