/** Auto-generated by discoverWidgetFiles — do not edit. */
export const widgetFiles: Record<string, { html?: string; md?: string; css?: string }> = {
  'file-widget': {
    html: 'widgets/file-widget/file-widget.widget.html',
    md: 'widgets/file-widget/file-widget.widget.md',
    css: 'widgets/file-widget/file-widget.widget.css',
  },
  'remote-widget': {
    html: 'http://localhost:4100/widgets/remote-widget/remote-widget.widget.html',
    css: 'http://localhost:4100/widgets/remote-widget/remote-widget.widget.css',
  },
  'nav': { css: 'widgets/nav/nav.widget.css' },
};
