/**
 * Generated Widgets Manifest
 *
 * DO NOT EDIT - This file is auto-generated by widget.generator.ts
 */

import type { WidgetsManifest } from '@emkodev/emroute';

export const widgetsManifest: WidgetsManifest = {
  widgets: [
    {
      name: 'article-card',
      modulePath: 'widgets/article-card/article-card.widget.ts',
      tagName: 'widget-article-card',
    },
    {
      name: 'counter-vanilla',
      modulePath: 'widgets/counter-vanilla/counter-vanilla.widget.ts',
      tagName: 'widget-counter-vanilla',
    },
    {
      name: 'element-ref',
      modulePath: 'widgets/element-ref/element-ref.widget.ts',
      tagName: 'widget-element-ref',
    },
    {
      name: 'failing',
      modulePath: 'widgets/failing/failing.widget.ts',
      tagName: 'widget-failing',
    },
    {
      name: 'file-widget',
      modulePath: 'widgets/file-widget/file-widget.widget.ts',
      tagName: 'widget-file-widget',
      files: {
        html: 'widgets/file-widget/file-widget.widget.html',
        md: 'widgets/file-widget/file-widget.widget.md',
        css: 'widgets/file-widget/file-widget.widget.css',
      },
    },
    {
      name: 'greeting',
      modulePath: 'widgets/greeting/greeting.widget.ts',
      tagName: 'widget-greeting',
    },
    {
      name: 'hydration-test',
      modulePath: 'widgets/hydration-test/hydration-test.widget.ts',
      tagName: 'widget-hydration-test',
    },
    {
      name: 'info-card',
      modulePath: 'widgets/info-card/info-card.widget.ts',
      tagName: 'widget-info-card',
    },
    {
      name: 'nav',
      modulePath: 'widgets/nav/nav.widget.ts',
      tagName: 'widget-nav',
      files: { css: 'widgets/nav/nav.widget.css' },
    },
    {
      name: 'remote-widget',
      modulePath: 'widgets/remote-widget/remote-widget.widget.ts',
      tagName: 'widget-remote-widget',
      files: {
        html: 'widgets/remote-widget/remote-widget.widget.html',
        css: 'widgets/remote-widget/remote-widget.widget.css',
      },
    },
    {
      name: 'search-filter',
      modulePath: 'widgets/search-filter/search-filter.widget.ts',
      tagName: 'widget-search-filter',
    },
  ],

  moduleLoaders: {
    'widgets/article-card/article-card.widget.ts': () =>
      import('./widgets/article-card/article-card.widget.ts'),
    'widgets/counter-vanilla/counter-vanilla.widget.ts': () =>
      import('./widgets/counter-vanilla/counter-vanilla.widget.ts'),
    'widgets/element-ref/element-ref.widget.ts': () =>
      import('./widgets/element-ref/element-ref.widget.ts'),
    'widgets/failing/failing.widget.ts': () => import('./widgets/failing/failing.widget.ts'),
    'widgets/file-widget/file-widget.widget.ts': () =>
      import('./widgets/file-widget/file-widget.widget.ts'),
    'widgets/greeting/greeting.widget.ts': () => import('./widgets/greeting/greeting.widget.ts'),
    'widgets/hydration-test/hydration-test.widget.ts': () =>
      import('./widgets/hydration-test/hydration-test.widget.ts'),
    'widgets/info-card/info-card.widget.ts': () =>
      import('./widgets/info-card/info-card.widget.ts'),
    'widgets/nav/nav.widget.ts': () => import('./widgets/nav/nav.widget.ts'),
    'widgets/remote-widget/remote-widget.widget.ts': () =>
      import('./widgets/remote-widget/remote-widget.widget.ts'),
    'widgets/search-filter/search-filter.widget.ts': () =>
      import('./widgets/search-filter/search-filter.widget.ts'),
  },
};
