/**
 * Generated Widgets Manifest
 *
 * DO NOT EDIT - This file is auto-generated by widget.generator.ts
 */

import type { WidgetsManifest } from '@emkodev/emroute';

export const widgetsManifest: WidgetsManifest = {
  widgets: [
    {
      name: 'article-card',
      modulePath: 'widgets/article-card/article-card.widget.ts',
      tagName: 'widget-article-card',
    },
    {
      name: 'card-container',
      modulePath: 'widgets/card-container/card-container.widget.ts',
      tagName: 'widget-card-container',
    },
    {
      name: 'code-block',
      modulePath: 'widgets/code-block/code-block.widget.ts',
      tagName: 'widget-code-block',
    },
    {
      name: 'content-tab',
      modulePath: 'widgets/content-tab/content-tab.widget.ts',
      tagName: 'widget-content-tab',
    },
    {
      name: 'counter-htm',
      modulePath: 'widgets/counter-htm/counter-htm.widget.ts',
      tagName: 'widget-counter-htm',
    },
    {
      name: 'counter-vanilla',
      modulePath: 'widgets/counter-vanilla/counter-vanilla.widget.ts',
      tagName: 'widget-counter-vanilla',
    },
    {
      name: 'element-ref',
      modulePath: 'widgets/element-ref/element-ref.widget.ts',
      tagName: 'widget-element-ref',
    },
    {
      name: 'failing',
      modulePath: 'widgets/failing/failing.widget.ts',
      tagName: 'widget-failing',
    },
    {
      name: 'file-widget',
      modulePath: 'widgets/file-widget/file-widget.widget.ts',
      tagName: 'widget-file-widget',
      files: {
        html: 'widgets/file-widget/file-widget.widget.html',
        md: 'widgets/file-widget/file-widget.widget.md',
        css: 'widgets/file-widget/file-widget.widget.css',
      },
    },
    {
      name: 'greeting',
      modulePath: 'widgets/greeting/greeting.widget.ts',
      tagName: 'widget-greeting',
    },
    {
      name: 'hero-banner',
      modulePath: 'widgets/hero-banner/hero-banner.widget.ts',
      tagName: 'widget-hero-banner',
    },
    {
      name: 'hydration-test',
      modulePath: 'widgets/hydration-test/hydration-test.widget.ts',
      tagName: 'widget-hydration-test',
    },
    {
      name: 'info-card',
      modulePath: 'widgets/info-card/info-card.widget.ts',
      tagName: 'widget-info-card',
    },
    {
      name: 'nav',
      modulePath: 'widgets/nav/nav.widget.ts',
      tagName: 'widget-nav',
      files: { css: 'widgets/nav/nav.widget.css' },
    },
    {
      name: 'overlay-demo',
      modulePath: 'widgets/overlay-demo/overlay-demo.widget.ts',
      tagName: 'widget-overlay-demo',
    },
    {
      name: 'recent-article',
      modulePath: 'widgets/recent-article/recent-article.widget.ts',
      tagName: 'widget-recent-article',
    },
    {
      name: 'remote-widget',
      modulePath: 'widgets/remote-widget/remote-widget.widget.ts',
      tagName: 'widget-remote-widget',
      files: {
        html: 'widgets/remote-widget/remote-widget.widget.html',
        css: 'widgets/remote-widget/remote-widget.widget.css',
      },
    },
    {
      name: 'search-filter',
      modulePath: 'widgets/search-filter/search-filter.widget.ts',
      tagName: 'widget-search-filter',
    },
    {
      name: 'stat-card',
      modulePath: 'widgets/stat-card/stat-card.widget.ts',
      tagName: 'widget-stat-card',
    },
    {
      name: 'tag-cloud',
      modulePath: 'widgets/tag-cloud/tag-cloud.widget.ts',
      tagName: 'widget-tag-cloud',
    },
  ],

  moduleLoaders: {
    'widgets/article-card/article-card.widget.ts': () =>
      import('./widgets/article-card/article-card.widget.ts'),
    'widgets/card-container/card-container.widget.ts': () =>
      import('./widgets/card-container/card-container.widget.ts'),
    'widgets/code-block/code-block.widget.ts': () =>
      import('./widgets/code-block/code-block.widget.ts'),
    'widgets/content-tab/content-tab.widget.ts': () =>
      import('./widgets/content-tab/content-tab.widget.ts'),
    'widgets/counter-htm/counter-htm.widget.ts': () =>
      import('./widgets/counter-htm/counter-htm.widget.ts'),
    'widgets/counter-vanilla/counter-vanilla.widget.ts': () =>
      import('./widgets/counter-vanilla/counter-vanilla.widget.ts'),
    'widgets/element-ref/element-ref.widget.ts': () =>
      import('./widgets/element-ref/element-ref.widget.ts'),
    'widgets/failing/failing.widget.ts': () => import('./widgets/failing/failing.widget.ts'),
    'widgets/file-widget/file-widget.widget.ts': () =>
      import('./widgets/file-widget/file-widget.widget.ts'),
    'widgets/greeting/greeting.widget.ts': () => import('./widgets/greeting/greeting.widget.ts'),
    'widgets/hero-banner/hero-banner.widget.ts': () =>
      import('./widgets/hero-banner/hero-banner.widget.ts'),
    'widgets/hydration-test/hydration-test.widget.ts': () =>
      import('./widgets/hydration-test/hydration-test.widget.ts'),
    'widgets/info-card/info-card.widget.ts': () =>
      import('./widgets/info-card/info-card.widget.ts'),
    'widgets/nav/nav.widget.ts': () => import('./widgets/nav/nav.widget.ts'),
    'widgets/overlay-demo/overlay-demo.widget.ts': () =>
      import('./widgets/overlay-demo/overlay-demo.widget.ts'),
    'widgets/recent-article/recent-article.widget.ts': () =>
      import('./widgets/recent-article/recent-article.widget.ts'),
    'widgets/remote-widget/remote-widget.widget.ts': () =>
      import('./widgets/remote-widget/remote-widget.widget.ts'),
    'widgets/search-filter/search-filter.widget.ts': () =>
      import('./widgets/search-filter/search-filter.widget.ts'),
    'widgets/stat-card/stat-card.widget.ts': () =>
      import('./widgets/stat-card/stat-card.widget.ts'),
    'widgets/tag-cloud/tag-cloud.widget.ts': () =>
      import('./widgets/tag-cloud/tag-cloud.widget.ts'),
  },
};
